// Hand-drawn 16×16 sprites. Each character maps to a palette key in palette.ts;
// '.' is transparent. Keep every row exactly 16 characters.

export const SPRITES = {
  coin: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kyyyyyyk....',
    '...kyywyyyyYk...',
    '...kywyyyyyYk...',
    '...kyyyYYyyYk...',
    '...kyyyYYyyYk...',
    '...kyyyYYyyYk...',
    '...kyyyYYyyYk...',
    '...kyyyyyyyYk...',
    '...kYyyyyyYYk...',
    '....kYYYYYYk....',
    '.....kkkkkk.....',
    '................',
    '................',
  ],
  star: [
    '................',
    '.......kk.......',
    '......kyyk......',
    '......kwyk......',
    '.....kywyyk.....',
    'kkkkkkyyyyykkkkk',
    'kyyyywyyyyyyyyYk',
    '.kyyyyyyyyyyyYk.',
    '..kyyyyyyyyyYk..',
    '...kyyyyyyyYk...',
    '...kyyyyyyyYk...',
    '..kyyyykkyyyYk..',
    '..kyyyk..kyyYk..',
    '.kyyyk....kyyYk.',
    '.kyyk......kYYk.',
    '.kkk........kkk.',
  ],
  heart: [
    '................',
    '................',
    '..kkkk....kkkk..',
    '.krrrrk..krrrrk.',
    'krwwrrrkkrrrrrRk',
    'krwrrrrrrrrrrrRk',
    'krrrrrrrrrrrrrRk',
    'krrrrrrrrrrrrrRk',
    '.krrrrrrrrrrrRk.',
    '..krrrrrrrrrRk..',
    '...krrrrrrrRk...',
    '....krrrrrRk....',
    '.....krrrRk.....',
    '......krRk......',
    '.......kk.......',
    '................',
  ],
  chest: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kbwbbbbbbbbk..',
    '.kbbbbbbbbbbbbk.',
    '.kyBBBBBBBBBByk.',
    '.kkkkkkkkkkkkkk.',
    '.kybbbbkkbbbbyk.',
    '.kybbbkyykbbbyk.',
    '.kybbbkYYkbbbyk.',
    '.kybbbbkkbbbbyk.',
    '.kyBBBBBBBBBByk.',
    '.kyDDDDDDDDDDyk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  chestOpen: [
    '..kkkkkkkkkkkk..',
    '.kBbbbbbbbbbbBk.',
    '.kBDDDDDDDDDDBk.',
    '.kkkkkkkkkkkkkk.',
    '.kyywyyyyyywyyk.',
    '.kyyyyywyyyyyYk.',
    '.kkkkkkkkkkkkkk.',
    '.kybbbbkkbbbbyk.',
    '.kybbbkyykbbbyk.',
    '.kybbbkYYkbbbyk.',
    '.kybbbbkkbbbbyk.',
    '.kyBBBBBBBBBByk.',
    '.kyDDDDDDDDDDyk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
  ],
  trophy: [
    '................',
    '...kkkkkkkkkk...',
    '.kkkwyyyyyyYkkk.',
    '.k.kwyyyyyyYk.k.',
    '.k.kwyyyyyyYk.k.',
    '..kkyyyyyyyYkk..',
    '...kyyyyyyYYk...',
    '....kyyyyyYk....',
    '.....kyyyYk.....',
    '......kyYk......',
    '......kyYk......',
    '.....kkyYkk.....',
    '....kYyyyyYk....',
    '...kBBBBBBBBk...',
    '...kkkkkkkkkk...',
    '................',
  ],
  scroll: [
    '................',
    '...kkkkkkkkkk...',
    '..kPWWWWWWWWPk..',
    '..kkPPPPPPPPkk..',
    '...kWWWWWWWWk...',
    '...kWEEEEEEWk...',
    '...kWWWWWWWWk...',
    '...kWEEEEWWWk...',
    '...kWWWWWWWWk...',
    '...kWEEEEEEWk...',
    '...kWWWWWWWWk...',
    '...kWEEEWWrrk...',
    '..kkkkkkkkkkkk..',
    '..kPWWWWWWWWPk..',
    '...kkkkkkkkkk...',
    '................',
  ],
  crown: [
    '................',
    '................',
    '................',
    '.kk....kk....kk.',
    '.kyk..kyyk..kyk.',
    '.kyyk.kyyk.kyyk.',
    '.kyyykkyykkyyyk.',
    '.kywyyyyyyyyyyk.',
    '.kyrryyccyyrryk.',
    '.kyrRyyCCyyrRyk.',
    '.kyyyyyyyyyyyyk.',
    '.kYYYYYYYYYYYYk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  robot: [
    '.......kk.......',
    '......kcck......',
    '.......kk.......',
    '.......kk.......',
    '..kkkkkkkkkkkk..',
    '.kLwLLLLLLLLLLk.',
    'kkLLkkkLLkkkLLkk',
    'keLLkckLLkckLLek',
    'keLLkkkLLkkkLLek',
    'kkLLLLLLLLLLLLkk',
    '.kLLLkvvvvkLLLk.',
    '.kLLLLLLLLLLLLk.',
    '.keeeeeeeeeeeek.',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  laptop: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..knnnnnnnnnnk..',
    '..knllnyyynnnk..',
    '..knnnppppnnnk..',
    '..knlllnnyynnk..',
    '..knnnnnnnnnnk..',
    '..kkkkkkkkkkkk..',
    '.kLLLLLLLLLLLLk.',
    'kLLeLeLeLeLeLLLk',
    'kEEEEEEEEEEEEEEk',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
  ],
  rocket: [
    '.......kk.......',
    '......krrk......',
    '.....krrrRk.....',
    '.....kWWWPk.....',
    '.....kWccPk.....',
    '.....kWcCPk.....',
    '.....kWWWPk.....',
    '.....kWWWPk.....',
    '....kkWWWPkk....',
    '...krkWWWPkrk...',
    '..krrkrrrRkrrk..',
    '..kkk.kkkk.kkk..',
    '......oyyo......',
    '.......yy.......',
    '.......oo.......',
    '................',
  ],
  calendar: [
    '................',
    '.....k....k.....',
    '..kkkkkkkkkkkk..',
    '..krrrrrrrrrrk..',
    '..krwrrrrrrrRk..',
    '..kkkkkkkkkkkk..',
    '..kWWWWWWWWWWk..',
    '..kWEWEWEWEWWk..',
    '..kWWWWWWWWWWk..',
    '..kWEWEWEWEWWk..',
    '..kWWWWWWWWWWk..',
    '..kWEWEWrrWWWk..',
    '..kWWWWWrrWWWk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
  ],
  hourglass: [
    '................',
    '..kkkkkkkkkkkk..',
    '..kBBBBBBBBBBk..',
    '...kWWWWWWWWk...',
    '...kWyyyyyyWk...',
    '....kWyyyyWk....',
    '.....kWyyWk.....',
    '......kWyk......',
    '......kWyk......',
    '.....kWWyWk.....',
    '....kWWWyWWk....',
    '...kWWWyyyWWk...',
    '...kWyyyyyyWk...',
    '..kBBBBBBBBBBk..',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  flag: [
    '................',
    '..kk............',
    '..kekkkkkkkkkk..',
    '..kekrrrrrrrrk..',
    '..kekrwwrrrrRk..',
    '..kekrrrrrrrRk..',
    '..kekrrrrrrRRk..',
    '..kekkkkkkkkkk..',
    '..kek...........',
    '..kek...........',
    '..kek...........',
    '..kek...........',
    '..kek...........',
    '.kkkkk..........',
    '.kBBBk..........',
    '.kkkkk..........',
  ],
  gem: [
    '................',
    '................',
    '................',
    '....kkkkkkkk....',
    '...kvwvvvvVVk...',
    '..kvwvvvvvvVVk..',
    '..kkkkkkkkkkkk..',
    '...kvvvvvvVVk...',
    '....kvvvvvVk....',
    '.....kvvvVk.....',
    '......kvVk......',
    '.......kk.......',
    '................',
    '................',
    '................',
    '................',
  ],
  lock: [
    '................',
    '................',
    '.....kkkkkk.....',
    '....kekkkkek....',
    '....kek..kek....',
    '....kek..kek....',
    '...kkkkkkkkkk...',
    '...kywyyyyyYk...',
    '...kyyykkyyYk...',
    '...kyyykkyyYk...',
    '...kyyyykyyYk...',
    '...kyyyyyyyYk...',
    '...kYYYYYYYYk...',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  chat: [
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kaaaaaaaaaak..',
    '.kaawaaaaaaaaak.',
    '.kawaaaaaaaaaak.',
    '.kaaawaawaawaak.',
    '.kaaaaaaaaaaaAk.',
    '..kaaaaaaaaaAk..',
    '..kaakkkkkkkk...',
    '.kaak...........',
    '.kkk............',
    '................',
    '................',
    '................',
    '................',
  ],
  shield: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kCCCCCCCCCCk..',
    '..kCcCCCCCCnnk..',
    '..kCCCCyyCCCnk..',
    '..kCCCyyyyCCnk..',
    '..kCCCCyyCCCnk..',
    '...kCCCCCCCnk...',
    '...kCCCCCCCnk...',
    '....kCCCCCnk....',
    '.....kCCCnk.....',
    '......kCnk......',
    '.......kk.......',
    '................',
    '................',
  ],
  bolt: [
    '................',
    '........kkkk....',
    '.......kyyyk....',
    '......kyyyk.....',
    '.....kyyyk......',
    '....kyyyykkkk...',
    '...kwyyyyyyyk...',
    '...kkkkyyyyk....',
    '......kyyyk.....',
    '.....kyyyk......',
    '....kyyyk.......',
    '....kyyk........',
    '...kyk..........',
    '...kk...........',
    '................',
    '................',
  ],
  check: [
    '................',
    '................',
    '................',
    '...........kkk..',
    '..........kgGk..',
    '.........kggk...',
    '.kk.....kggk....',
    'kgGk...kggk.....',
    '.kgGk.kggk......',
    '..kgGkggk.......',
    '...kgggk........',
    '....kgk.........',
    '.....k..........',
    '................',
    '................',
    '................',
  ],
  sword: [
    '................',
    '............kkk.',
    '...........kLwk.',
    '..........kLwk..',
    '.........kLwk...',
    '........kLwk....',
    '.......kLwk.....',
    '..kk..kLwk......',
    '..kyk.kLk.......',
    '...kykkk........',
    '....kyk.........',
    '...kBkyk........',
    '..kBk.kyk.......',
    '.kBk...kk.......',
    '.kk.............',
    '................',
  ],
  mail: [
    '................',
    '................',
    '................',
    '.kkkkkkkkkkkkkk.',
    '.kWkWWWWWWWWkWk.',
    '.kWWkWWWWWWkWWk.',
    '.kWWWkWWWWkWWWk.',
    '.kWWWWkkkkWWWWk.',
    '.kWWWWWWWWWWWWk.',
    '.kWWWWWWWWWWWWk.',
    '.kPPPPPPPPPPPPk.',
    '.kkkkkkkkkkkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  potion: [
    '................',
    '......kkkk......',
    '......kBBk......',
    '......kkkk......',
    '.......kk.......',
    '......kLLk......',
    '.....kLwLLk.....',
    '....kvvvvvvk....',
    '...kvwvvvvvVk...',
    '...kvvvvvvvVk...',
    '...kvvvvvvVVk...',
    '....kVVVVVVk....',
    '.....kkkkkk.....',
    '................',
    '................',
    '................',
  ],
  map: [
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '..kWWPWWWPWWWk..',
    '..kWrrWWPWWWPk..',
    '..kWrrWPWWgWWk..',
    '..kWWPWWWggWPk..',
    '..kPWWWkWWWWWk..',
    '..kWWWkrkWPWWk..',
    '..kWPWWkWWWWWk..',
    '..kWWWPWWWPWWk..',
    '..kkkkkkkkkkkk..',
    '................',
    '................',
    '................',
    '................',
  ],
  qr: [
    '................',
    '.kkkkk....kkkkk.',
    '.kwwwk.kk.kwwwk.',
    '.kwkwk..k.kwkwk.',
    '.kwwwk.k..kwwwk.',
    '.kkkkk.kk.kkkkk.',
    '.......k........',
    '.kk.kk.kkk.k.kk.',
    '..k.k...k.kk..k.',
    '.......k.k..k...',
    '.kkkkk..kk.kk.k.',
    '.kwwwk.k...k..k.',
    '.kwkwk.kkk.kk...',
    '.kwwwk..k.k..kk.',
    '.kkkkk.kk..kk.k.',
    '................',
  ],
} as const

export type SpriteName = keyof typeof SPRITES

// ---- Characters (12×16) with swappable palette slots ----
// h = hair, s/S = skin, t/T = shirt, u = pants
const CHAR_DOWN_A = [
  '....kkkk....',
  '..kkhhhhkk..',
  '.khhhhhhhhk.',
  '.khhhhhhhhk.',
  '.khsssssshk.',
  '.kskssssksk.',
  '.kssssssssk.',
  '..ksssssSk..',
  '...kkSSkk...',
  '..kttttttk..',
  '.kttttttTTk.',
  '.ksttttttsk.',
  '..kTTTTTTk..',
  '..kuuuuuuk..',
  '..kuk..kuk..',
  '..kk....kk..',
]
const CHAR_DOWN_B = [
  ...CHAR_DOWN_A.slice(0, 13),
  '..kuuuuuuk..',
  '...kukkuk...',
  '...kk..kk...',
]
const CHAR_UP_A = [
  '....kkkk....',
  '..kkhhhhkk..',
  '.khhhhhhhhk.',
  '.khhhhhhhhk.',
  '.khhhhhhhhk.',
  '.kshhhhhhsk.',
  '.khhhhhhhhk.',
  '..khhhhhhk..',
  '...kkSSkk...',
  '..kttttttk..',
  '.kTttttttTk.',
  '.ksTttttTsk.',
  '..kTTTTTTk..',
  '..kuuuuuuk..',
  '..kuk..kuk..',
  '..kk....kk..',
]
const CHAR_UP_B = [
  ...CHAR_UP_A.slice(0, 13),
  '..kuuuuuuk..',
  '...kukkuk...',
  '...kk..kk...',
]
const CHAR_RIGHT_A = [
  '....kkkk....',
  '...khhhhkk..',
  '..khhhhhhhk.',
  '..khhhhhhhk.',
  '..khhhhsssk.',
  '..khhssskskk',
  '..khssssssk.',
  '...kssssSk..',
  '....kkSSk...',
  '...kttttk...',
  '...kttttTk..',
  '...kttstTk..',
  '...kTTTTk...',
  '...kuuuuk...',
  '..kuk..kuk..',
  '..kk....kk..',
]
const CHAR_RIGHT_B = [
  ...CHAR_RIGHT_A.slice(0, 13),
  '...kuuuuk...',
  '....kukk....',
  '....kkk.....',
]

const mirror = (rows: string[]) => rows.map((r) => r.split('').reverse().join(''))

export const CHAR_FRAMES = {
  down: [CHAR_DOWN_A, CHAR_DOWN_B],
  up: [CHAR_UP_A, CHAR_UP_B],
  right: [CHAR_RIGHT_A, CHAR_RIGHT_B],
  left: [mirror(CHAR_RIGHT_A), mirror(CHAR_RIGHT_B)],
}
export type Facing = keyof typeof CHAR_FRAMES

// a type alias (not an interface) so it is assignable to a palette swap map
export type CharLook = {
  h: string
  s: string
  S: string
  t: string
  T: string
  u: string
}

export const LOOKS: CharLook[] = [
  { h: '#33241e', s: '#e3a873', S: '#c4834f', t: '#e04848', T: '#a32d3d', u: '#3d3550' },
  { h: '#1d1a22', s: '#c98c5a', S: '#a86c3e', t: '#3f7fd8', T: '#2a4a8a', u: '#4a4038' },
  { h: '#4a2a1a', s: '#eebb8a', S: '#cf9867', t: '#5fb653', T: '#3c8d3f', u: '#2d3a5a' },
  { h: '#1d1a22', s: '#b7794a', S: '#94592f', t: '#ffd23f', T: '#e0a526', u: '#3d3550' },
  { h: '#33241e', s: '#d99a66', S: '#b77a48', t: '#8a63ff', T: '#5b3fc4', u: '#2d3a5a' },
  { h: '#1d1a22', s: '#e3a873', S: '#c4834f', t: '#ff7aa8', T: '#d0507e', u: '#4a4038' },
  { h: '#5a3520', s: '#c98c5a', S: '#a86c3e', t: '#f28c28', T: '#c4651a', u: '#3d3550' },
  { h: '#1d1a22', s: '#eebb8a', S: '#cf9867', t: '#4de1ff', T: '#2fa8c8', u: '#2d3a5a' },
]

// ---- 3×5 bitmap font for in-world signs ----
export const FONT_3x5: Record<string, string[]> = {
  A: ['.#.', '#.#', '###', '#.#', '#.#'],
  B: ['##.', '#.#', '##.', '#.#', '##.'],
  C: ['.##', '#..', '#..', '#..', '.##'],
  D: ['##.', '#.#', '#.#', '#.#', '##.'],
  E: ['###', '#..', '##.', '#..', '###'],
  F: ['###', '#..', '##.', '#..', '#..'],
  G: ['.##', '#..', '#.#', '#.#', '.##'],
  H: ['#.#', '#.#', '###', '#.#', '#.#'],
  I: ['###', '.#.', '.#.', '.#.', '###'],
  J: ['..#', '..#', '..#', '#.#', '.#.'],
  K: ['#.#', '#.#', '##.', '#.#', '#.#'],
  L: ['#..', '#..', '#..', '#..', '###'],
  M: ['#.#', '###', '###', '#.#', '#.#'],
  N: ['##.', '#.#', '#.#', '#.#', '#.#'],
  O: ['.#.', '#.#', '#.#', '#.#', '.#.'],
  P: ['##.', '#.#', '##.', '#..', '#..'],
  Q: ['.#.', '#.#', '#.#', '##.', '.##'],
  R: ['##.', '#.#', '##.', '#.#', '#.#'],
  S: ['.##', '#..', '.#.', '..#', '##.'],
  T: ['###', '.#.', '.#.', '.#.', '.#.'],
  U: ['#.#', '#.#', '#.#', '#.#', '###'],
  V: ['#.#', '#.#', '#.#', '#.#', '.#.'],
  W: ['#.#', '#.#', '###', '###', '#.#'],
  X: ['#.#', '#.#', '.#.', '#.#', '#.#'],
  Y: ['#.#', '#.#', '.#.', '.#.', '.#.'],
  Z: ['###', '..#', '.#.', '#..', '###'],
  '0': ['###', '#.#', '#.#', '#.#', '###'],
  '1': ['.#.', '##.', '.#.', '.#.', '###'],
  '2': ['##.', '..#', '.#.', '#..', '###'],
  '3': ['##.', '..#', '.#.', '..#', '##.'],
  '4': ['#.#', '#.#', '###', '..#', '..#'],
  '5': ['###', '#..', '##.', '..#', '##.'],
  '6': ['.##', '#..', '###', '#.#', '###'],
  '7': ['###', '..#', '.#.', '.#.', '.#.'],
  '8': ['###', '#.#', '###', '#.#', '###'],
  '9': ['###', '#.#', '###', '..#', '##.'],
  '!': ['.#.', '.#.', '.#.', '...', '.#.'],
  '>': ['#..', '.#.', '..#', '.#.', '#..'],
  '<': ['..#', '.#.', '#..', '.#.', '..#'],
  '-': ['...', '...', '###', '...', '...'],
  ':': ['...', '.#.', '...', '.#.', '...'],
  '.': ['...', '...', '...', '...', '.#.'],
  ' ': ['...', '...', '...', '...', '...'],
}
